name: Bug report
description: Create a report to help us improve
title: '[Bug] '
labels: ['bug']
assignees:
  - xfqwdsj
body:
  - type: markdown
    attributes:
      value: |
        *(For Chinese users)* **Issue标题请使用英文，内容可用中文**
  - type: checkboxes
    id: searched_existing_issues
    attributes:
      label: Searched Existing Issues
      description: Please confirm you have searched for existing issues before submitting a new one.
      options:
        - label: I have searched for existing issues and did not find a similar one.
          required: true
  - type: textarea
    id: bug_description
    attributes:
      label: Bug Description
      description: Clearly describe the bug.
      placeholder: e.g., App crashes on launch
    validations:
      required: true
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide step-by-step instructions to reproduce the issue.
      placeholder: e.g., 1. Open the app 2. Tap on 'Hide USB debugging' 3. Observe crash
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen.
      placeholder: e.g., The switch state changed without crashing
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## How to provide screenshots correctly?

        Since a screenshot may be too long to read, please use the following format to provide screenshots:

        ```markdown
        <details><summary>Screenshots</summary>
        <!-- Paste your screenshots here -->
        </details>
        ```
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Attach screenshots to help illustrate the issue.
      placeholder: Follow the format below to provide screenshots.
  - type: textarea
    id: device_info
    attributes:
      label: Device Details
      description: Provide device and OS details.
      placeholder: |
        e.g., Device: Xiaomi 14, OS: Xiaomi Hyper OS 1.0.23.12.4.DEV; Android 14
  - type: markdown
    attributes:
      value: |
        ## How to provide logs correctly?

        Since logs can be lengthy, please use the following format to provide logs:

        - **Option 1**: Paste the log file directly in the text area below.
        - **Option 2**: Use the following format to provide log text:

          ````markdown
          <details><summary>Logs</summary>
          <!-- Paste your log text in the code block below -->
          ```

          ```
          </details>
          ````

        This helps us diagnose the issue more effectively.
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Provide logs to help diagnose the issue.
      placeholder: Follow the format below to provide logs.
      validations:
        required: true
  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other relevant information.
      placeholder: e.g., Related issues
